config/routes.rb
Rails.application.routes.draw do
  get 'invitation/create'
  root 'welcome#index'
  devise_for :users
  resources :users, only: [:show]
  resources :events, only: %i[show create new] do 
    resources :invites
  end
  resources :invitations, only: %i[create]
  resources :attendances, only: %i[create index]
  post '/events/:event_id', to: 'attend#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :location, presence: true
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :creates, foreign_key: 'event_id'
  has_many :creators, through: :creates, source: :user
  has_many :invitations
  has_many :users_invited, through: :invitations, source: :invitee

  has_many :attendances, foreign_key: 'event_id'
  has_many :users_attendants, through: :attendances, source: :user

  has_many :sign_ups, foreign_key: 'Event_id'
  has_many :users_signed_up, through: :sign_ups, source: :User

  scope :prev_events, -> { where('date < ?', Time.now) }
  scope :upcoming_events, -> { where('date > ?', Time.now) }

  def past?
    today = Time.now.to_s.split(' ')[0]
    if date > today
      'Coming'
    elsif date == today
      'Today'
    else
      'Past'
    end
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invitor, class_name: 'User'
  belongs_to :invitee, class_name: 'User'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users_invited, class_name: 'Invitation', foreign_key: 'invitor_id'
  has_many :users_invitors, class_name: 'Invitation', foreign_key: 'invitee_id'
  has_many :invitations, through: :users_invited, source: :invitee
  has_many :invites, through: :users_invitors, source: :invitor
  has_many :events, foreign_key: 'creator_id'

  def check_invited?(event)
    event.users_invited.include?(self)
  end

  def check_signed_up?(event)
    return true if event.users_signed_up.include?(self)
  end

  def check_events(invitations)
    arr = []
    invitations.each do |i|
      arr << i.event
    end
    arr
  end

  def prev_events(events)
    previus = []
    events.each do |e|
      previus << e if e.date < Time.now
    end
    previus
  end

  def attended(events)
    arr = []
    events.each do |e|
      inv = Invitation.find_by(invitee_id: id, event_id: e.id)
      cr = Invitation.find_by(invitor_id: id, event_id: e.id)
      arr << inv.event if inv.status == true
      arr << cr.event if cr
    end
    arr
  end

  def coming_events(events)
    upcoming = []
    events.each do |e|
      upcoming << e if e.date > Time.now
    end
    upcoming
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/attend_controller.rb
class AttendController < ApplicationController
  def create
    inv = Invitation.find_by(invitee_id: current_user.id, event_id: params[:event])
    inv.status = true
    inv.save
    redirect_to root_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
    @users = User.all
    @invitation = Invitation.new
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      user = User.find(params[:creator_id])
      invitation = Invitation.new
      invitation.status = true
      invitation.invitor = user
      invitation.invitee = user
      invitation.event = @event
      invitation.save
      redirect_to root_path
    else
      flash[:alert] = 'Invalid Parameters'
      render 'new'
    end
  end

  def event_params
    params.require(:event).permit(:name, :description, :location, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    @invitation = Invitation.new
    @invitation.invitor_id = params[:invitator]
    @invitation.invitee_id = params[:invitee]
    @invitation.event_id = params[:event]
    @invitation.save
    redirect_to event_path(@invitation.event_id)
  end

  def invitation_params
    params.require(:invitation).permit(:invitor, :invitee, :event)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @events = current_user.events
    @past_events = current_user.events.prev_events
    @upcoming_events = Invitation.where(invitee: current_user)
    @all_events = current_user.check_events(@upcoming_events)
    @coming = current_user.coming_events(@all_events)
    @prev = current_user.prev_events(@all_events)
    @attended = current_user.attended(@prev)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.order(:date)
    @past_events = Event.prev_events
    @upcoming_events = Event.upcoming_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def accept_invitation
    render 'events/accepinv' if current_user.check_invited?(@event) && @event.creator != current_user
  end

  def invite_user(user, event)
    render 'events/invite', user: user, event: event if !user.check_invited?(event) && @event.creator == current_user
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_accepinv.html.erb
    <%= form_with url: '/events/:event_id' , local: true, method: :POST do |f| %>
      <%= f.hidden_field :user, value: current_user.id %>
      <%= f.hidden_field :event, value: @event.id %>
      <button type="submit" class="btn btn-primary">Accept invitation</button>
    <% end %>

app/views/events/_invite.html.erb
            
            <li class="list-group-item"> <%= user.email %></li>
            <li class="list-group-item"> 
            <div class="form-group">
              <%= form_with url: invitations_path , local: true, method: :POST do |f| %>
                <%= f.hidden_field :invitator, value: current_user.id %>
                <%= f.hidden_field :invitee, value: user.id %>
                <%= f.hidden_field :event, value: event.id %>
                <button type="submit" class="btn btn-primary">Invite User</button>
              <% end %>
              </div></li>

app/views/events/new.html.erb
<%= form_with model: @event, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Event Name'%>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Description'%>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control', placeholder: 'Event Location'%>
  </div>
  <div class="form-group">
    <%= f.label :date %>
    <%= f.date_field :date, class: 'form-control', placeholder: 'Event Date'%>
  </div>
  <div class="form-group">
    <%= f.label :invitedlist %>
    <%= text_field_tag(:invitedlist) %>
    <%=  hidden_field_tag(:user_now_id, value = current_user.id) %>
  </div>
    <div class="form-group">
    <%=  hidden_field_tag(:creator_id, value = current_user.id) %>
  </div>
  <button type="submit" class="btn btn-primary">Create Event</button>
<% end %>

app/views/events/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"> <%= @event.name %> </h1>
  <p class="lead"> <%= @event.description %> </p>
  <hr class="my-4">
  <p> <%= @event.date %> </p>
  <div class="button d-flex justify-content-between">

  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  <%= accept_invitation %>

</div>
<div class="row">
  <div class="col-4">
  <h4 class="h5"> Guest List </h4>
  <div class="card" style="width: 18rem;">
    <ul class="list-group list-group-flush">
      <% @event.invitations.each do |invitation| %>
        <li class="list-group-item"> <%= invitation.invitee.email %> </li>
        <% end %>
    </ul>
  </div>
  </div>

  <div class="col-4">
    <h4 class="h5 mt-3"> List of all users </h4>
    <div class="card" style="width: 18rem;">
      <ul class="list-group list-group-flush">
        <% @users.each do |user| %>
            <%= invite_user(user, @event) %>
          <% end %>
      </ul>
    </div> 
  </div>

app/views/invitation/create.html.erb
<h1>Invitation#create</h1>
<p>Find me in app/views/invitation/create.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if signed_in? %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'create events', new_event_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
       <%= link_to current_user.email, user_path(current_user), class:"nav-link dropdown-toggle", 'data-toggle' => 'dropdown'  %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="dropdown-divider"></div>
          <%= link_to 'view profile', user_path(current_user), class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <%= link_to 'events', '#', class:"nav-link dropdown-toggle", 'data-toggle' => 'dropdown'  %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'All events', root_path , class: "dropdown-item" %>
          </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0 mr-2" type="submit">Search</button>
      <%= link_to 'logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0" %>
    </form>
    <% else %>
      <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0 mr-2" type="submit">Search</button>
      <%= link_to 'register', new_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0" %>
      <%= link_to 'sign in', new_user_session_path, class: "btn btn-outline-success my-2 my-sm-0" %>
    </form>
    <% end %>
  </div>
</nav>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render 'layouts/header'%>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/index.html.erb
<div class="jumbotron mt-4">

 <h2>Attended events<h3>
 <% @attended.each do |att| %>
  <% if att.user == current_user %>
    <div class="card">
    <div class="card-header">
    <small class="text-muted"> <%= att.event.date.split('-').reverse.join('-') %> </small>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%=att.event.name%></h5>
    </div>
  </div>
  <%end%>
 <%end%>

 <h3>upcoming events<h3>
 <% @event.each do |e| %>
  <% if e.past? == 'Coming'%>
  <div class="card">
      <div class="card-header">
        <small class="text-muted"> <%= e.date.split('-').reverse.join('-') %> </small>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%=e.name%></h5>
      </div>
    </div>
    <% end %>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="jumbotron mt-4">
  <p class='h4'>Past events</p>

  <% @prev.each do |e| %>
    <h1 class="h3"> <%= e.name %> </h1>
    <p class="lead"> <%= e.description %> </p>
    <hr class="my-4">
    <p> <%= e.date.split('-').reverse.join('-') %>  </p>
    <div class="button d-flex justify-content-between">
      <% end %>

</div>
</div>

<div class="jumbotron mt-4">
  <p class='h4'>Upcomming events</p>

  <% @coming.each do |e| %>
    <h1 class="h3"> <%= e.name %> </h1>
    <p class="lead"> <%= e.description %> </p>
    <hr class="my-4">
    <p> <%= e.date.split('-').reverse.join('-') %>  </p>
    <div class="button d-flex justify-content-between">
      <% end %>

</div>
</div>

<div class="jumbotron mt-4">
     <p class='h4'>Attended events</p>

  <% @attended.each do |e| %>
    <h1 class="h3"> <%= e.name %> </h1>
    <p class="lead"> <%= e.description %> </p>
    <hr class="my-4">
    <p> <%= e.date.split('-').reverse.join('-') %>  </p>
    <div class="button d-flex justify-content-between">
      <% end %>

</div>
</div>

app/views/welcome/index.html.erb
<h3 class="h4 mt-4">List of all Events in the Past</h3>

<% @past_events.each do |event| %>
  <div class="card">
  <div class="card-header">
    <%= event.past? %>
    <small class="text-muted"> <%= event.date.split('-').reverse.join('-') %> </small>
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= event.name %> </h5>
    <p class="card-text"> <%= event.description %> </p>
    <%= link_to 'See More', event_path(event), class: 'btn btn-primary' %>
  </div>
</div>

<% end %>

<h3 class="h4 mt-4">List of all Events in the Future</h3>

<% @upcoming_events.each do |event| %>
  <div class="card">
  <div class="card-header">
    <%= event.past? %>
    <small class="text-muted"> <%= event.date.split('-').reverse.join('-') %> </small>
  </div>
  <div class="card-body">
    <h5 class="card-title"> <%= event.name %> </h5>
    <p class="card-text"> <%= event.description %> </p>
    <%= link_to 'See More', event_path(event), class: 'btn btn-primary' %>
  </div>
</div>

<% end %>